# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-03-23 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celebs_id', models.CharField(max_length=20, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='NAME')),
            ],
        ),
    ]
