# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-03-23 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20210323_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='person',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
