# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-04-08 22:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post2',
            name='shows_id',
        ),
    ]
